# Generated by Django 5.2.8 on 2025-11-09 04:21

import uuid
from django.db import migrations


def populate_uuids(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    for user in CustomUser.objects.filter(uuid__isnull=True):
        user.uuid = uuid.uuid4()
        user.save(update_fields=['uuid'])


def reverse_populate_uuids(apps, schema_editor):
    # No need to reverse - we'll just leave UUIDs as they are
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_uuids, reverse_populate_uuids),
    ]
